### ISSUE TITLE
error when rule files are not yaml yml or jsonnnet

### ISSUE THREAD

**Issue by tizki** [FUSAKLA/promruval#94]
# issue description
my rule files have the suffix .rules 
it used to work properly earlier, but after I updated proruval version, it fails on
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x60f85b]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000120f58)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d
panic({0x101bc00?, 0x1b984b0?})
        /home/tidhar/sdk/go1.23.2/src/runtime/panic.go:785 +0x132
gopkg.in/yaml%2ev3.yaml_reader_read_handler(0x10d9320?, {0xc0004f2800?, 0x18?, 0x47453f?})
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/apic.go:74 +0x1b
gopkg.in/yaml%2ev3.yaml_parser_update_raw_buffer(0xc0002fc408)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/readerc.go:99 +0xf4
gopkg.in/yaml%2ev3.yaml_parser_determine_encoding(0xc0002fc408)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/readerc.go:50 +0x45
gopkg.in/yaml%2ev3.yaml_parser_update_buffer(0xc0002fc408, 0x1)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/readerc.go:139 +0x47
gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token(0xc0002fc408)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:689 +0x3b
gopkg.in/yaml%2ev3.yaml_parser_fetch_more_tokens(0xc0002fc408)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:677 +0x18c
gopkg.in/yaml%2ev3.peek_token(0xc0002fc408)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:69 +0x25
gopkg.in/yaml%2ev3.yaml_parser_parse_stream_start(0xc0002fc408, 0xc0002fc6b8)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:232 +0x32
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0x470f1d?, 0x7f8456ae4f18?)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:155 +0x39
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc000120ed8?, 0x1dbe980?)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:129 +0x7c
gopkg.in/yaml%2ev3.(*parser).expect(0xc0002fc408, 0x1)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:82 +0x3b
gopkg.in/yaml%2ev3.(*parser).init(...)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:67
gopkg.in/yaml%2ev3.(*parser).parse(0xc0002fc408)
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:148 +0x65
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc000121758, {0x10496e0, 0xc000104700})
        /home/tidhar/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:123 +0x10a
github.com/fusakla/promruval/v3/pkg/validate.Files({0xc0001ef680, 0x1, 0xfad0c0?}, {0xc0004b85b8, 0x1, 0x1dbe980?}, {0x11b2c88, 0x19}, {0x11a94a2, 0x12}, ...)
        /home/tidhar/go/src/promruval/pkg/validate/validate.go:80 +0xcde
main.main()
        /home/tidhar/go/src/promruval/main.go:198 +0xb46
```

it seems that validate.go checks if the files is yaml, yml or json, but if it's not any of them it just continues with a nil yamlReader 

# steps to reproduce:
create a rule file that ends with .rules and run
```
validate --config-file examples/check_rules.yaml examples/example.rules
```

# expected behavior:
support yaml files that have a different suffix

**Comment by FUSAKLA** [comment]
Hi, thanks for the report!

Sorry to hear that, I can confirm and reproduce it. Will fix it ASAP

**Comment by FUSAKLA** [comment]
I automatically assumed that the behavior was to skip such files, but TBH I'm a bit surprised that it processed them anyway :D

But yes, you are right. I'll revert it back to the former behavior.
